apiVersion: apps/v1
kind: Deployment
metadata:
  name: __DEPLOY_NAME__
  namespace: __NAMESPACE__
  labels:
    app: __APP_LABEL__
spec:
  selector:
    matchLabels:
      app: __APP_LABEL__
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: __APP_LABEL__
    spec:
      containers:
        - image: __IMAGE_FULL_NAME__
          name: __CONTAINER_NAME__
          env:
            - name: CONFIG_FILE
              value: __CONFIG_FILE__
            - name: RUST_LOG
              value: info
