FROM ubuntu:bionic

RUN apt-get update \
 && apt-get install -y \
 libssl-dev \
 libzmq3-dev

WORKDIR /root/
ENV PATH=$PATH:/root/bin \
    CARGO_INCREMENTAL=0

COPY config-test.yaml .
COPY config-prod.yaml .
COPY target/release/app ./app
CMD ["./app"]

