FROM rust:latest

RUN apt-get update \
 && apt-get install -y \
 curl \
 gcc \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 unzip

# For Building Protobufs
RUN set -eux; \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        i386) url='https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_32.zip' ;; \
        amd64) url='https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip' ;; \
    esac; \
    wget -q -O protoc.zip "$url"; \
    unzip -d /usr/local protoc.zip; \
    rm protoc.zip

RUN echo '[source.crates-io]' >> $CARGO_HOME/config \
    && echo 'replace-with = "vendored-sources"' >> $CARGO_HOME/config \
    && echo '[source.vendored-sources]' >> $CARGO_HOME/config \
    && echo 'directory = "/usr/src/myapp/vendor"' >> $CARGO_HOME/config

RUN rustup component add rustfmt